#########################################
#            Dockerfile verificado      #
#########################################
#########################################
#            BUILD PROCESS              #
#########################################

FROM openjdk:8-jdk-alpine as build

LABEL Author="Alejo Gutierrez"

WORKDIR /workspace/app

# /workspace/app
COPY ./mvnw.cmd   .
COPY ./mvnw       .
COPY ./.mvn       .mvn

COPY ./pom.xml    .
COPY ./src        src
COPY ./WebContent WebContent

RUN ./mvnw clean install -DskipTests

#######################################
#            RUN PROCESS              #
#######################################

FROM tomcat:8.5-jre8-alpine
LABEL maintainer="alejox.gutierrez@gmail.com"

# mvn install pone el war en el directorio "${HOME}/.m2/" 
# COPY --from=build "${HOME}/.m2/" /usr/local/tomcat/webapps/webapp

# pero el comando build lo deja tambien en tarjet/
COPY --from=build "/workspace/app/target/*.war" /usr/local/tomcat/webapps/cifrados.war

EXPOSE 8080

CMD ["catalina.sh", "run"]