#########################################
#            BUILD PROCESS              #
#########################################
FROM openjdk:8-jdk-alpine as build

WORKDIR /workspace/app

# /workspace/app
COPY ./mvnw.cmd   .
COPY ./mvnw       .
COPY ./.mvn       .

COPY ./pom.xml    .
COPY ./src        .

RUN ./mvnw clean install -DskipTests

#######################################
#            RUN PROCESS              #
#######################################

FROM tomcat:9.0.1-jre8-alpine
LABEL maintainer="alejox.gutierrez@gmail.com"

# mvn install pone el war en el directorio "${HOME}/.m2/" 
# COPY --from=build "${HOME}/.m2/" /usr/local/tomcat/webapps/webapp

# pero el comando build lo deja tambien en tarjet/
COPY --from=build "/workspace/app/tarjet/*.war" /usr/local/tomcat/webapps/webapp

EXPOSE 8080

CMD ["catalina.sh", "run"]